CRUD DienstProfiel aanmaken toegevoegd + DTO's, Controllers en Reposi…
FrancescaWiegman/mijnZorgRooster pull request #8
Opened 2019-01-12 16:07 UTC by cpadikken

…tories voor Dienst en Rooster.

Kan wat mij betreft worden samengevoegd met de Master, want werkt. Zit ook al wat voorwerk in voor het aanmaken van de roosters en diensten. NB. De Branch die gewoon "Charlotte" heet is wat mij betreft hiermee overbodig en kan weg.

2019-01-12 17:09 UTC, FrancescaWiegman reviewed
Volgens mij prima.

2019-01-13 15:57 UTC, mcvermeulen commented
Je hoeft niet voor elke entity een nieuwe repository aan te maken, daarom heb ik juist een GenericRepository toegevoegd.
Dus ipv:
```
public IDienstProfielRepository DienstProfielRepository
{
      get { return _dienstProfielRepository ?? (_dienstProfielRepository = new DienstProfielRepository(_context)); }
 }
```
Kan je zeggen:
```
public IGenericRepository<Dienst> DienstRepository
 {
      get { return _dienstRepository ?? (_dienstRepository = new GenericRepository<Dienst>(_context)); }
}     
```

2019-01-13 16:07 UTC, mcvermeulen requested changes
Je hoeft niet voor elke entity een nieuwe repository aan te maken, daarom heb ik juist een GenericRepository toegevoegd.
Dus ipv:
```
public IDienstProfielRepository DienstProfielRepository
{
      get { return _dienstProfielRepository ?? (_dienstProfielRepository = new DienstProfielRepository(_context)); }
 }
```
Kan je zeggen:
```
public IGenericRepository<Dienst> DienstRepository
 {
      get { return _dienstRepository ?? (_dienstRepository = new GenericRepository<Dienst>(_context)); }
}     
```
Dan hebben we niet voor elke entity een nieuw repository bestand nodig.
Dat is alleen nodig als je specifieke functies wil toevoegen aan de repository, zoals bv methoden voor het ophalen van relational data. Dan maak je wel een eigen aan, die weer extend van de generic

2019-01-13 16:17 UTC, mcvermeulen commented
Ik heb de conflicts alvast opgelost

2019-01-13 16:55 UTC, cpadikken commented
In de volgende push zal dit in orde zijn.

2019-01-13 21:05 UTC, cpadikken commented
De Repositories zijn nu Generic, zoals je vroeg. Ik heb bovendien nu CRUD acties voor Roosters toegevoegd, met wat aanvullende functionaliteiten via de RoosterService. Het overzicht in de Index view is nu bovendien sorteerbaar. Als jullie dat zelf ook willen gebruiken in jullie indexes, dan kan dat heel eenvoudig. 

Hierna moet ik nog zorgen dat er lege diensten aan een Rooster gehangen kunnen worden, en dat een Dienst een DienstProfiel krijgt.

2019-01-14 17:50 UTC, mcvermeulen approved these changes

2019-01-14 18:59 UTC, merged